/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as DashboardTribeIndexRouteImport } from './routes/_dashboard/tribe/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardStreamStudioRouteImport } from './routes/_dashboard/stream/studio'
import { Route as DashboardStreamListRouteImport } from './routes/_dashboard/stream/list'
import { Route as DashboardWebsiteThemesIndexRouteImport } from './routes/_dashboard/website/themes/index'
import { Route as DashboardWebsiteMessagesIndexRouteImport } from './routes/_dashboard/website/messages/index'
import { Route as DashboardWebsiteHomeIndexRouteImport } from './routes/_dashboard/website/home/index'
import { Route as DashboardWebsiteAnalyticsIndexRouteImport } from './routes/_dashboard/website/analytics/index'
import { Route as DashboardTribePostsIndexRouteImport } from './routes/_dashboard/tribe/posts/index'
import { Route as DashboardTribeMessagesIndexRouteImport } from './routes/_dashboard/tribe/messages/index'
import { Route as DashboardTribeMembershipTiersIndexRouteImport } from './routes/_dashboard/tribe/membership-tiers/index'
import { Route as DashboardTribeMembersIndexRouteImport } from './routes/_dashboard/tribe/members/index'
import { Route as DashboardStoreSettingsIndexRouteImport } from './routes/_dashboard/store/settings/index'
import { Route as DashboardStoreProductsIndexRouteImport } from './routes/_dashboard/store/products/index'
import { Route as DashboardStoreOrdersIndexRouteImport } from './routes/_dashboard/store/orders/index'
import { Route as DashboardStoreMusicIndexRouteImport } from './routes/_dashboard/store/music/index'
import { Route as DashboardSocialMediaConnectionsIndexRouteImport } from './routes/_dashboard/social-media/connections/index'
import { Route as DashboardSmartLinksTemplatesIndexRouteImport } from './routes/_dashboard/smart-links/templates/index'
import { Route as DashboardSmartLinksLinksIndexRouteImport } from './routes/_dashboard/smart-links/links/index'
import { Route as DashboardEventsSalesIndexRouteImport } from './routes/_dashboard/events/sales/index'
import { Route as DashboardEventsListIndexRouteImport } from './routes/_dashboard/events/list/index'
import { Route as DashboardEmailsTemplatesIndexRouteImport } from './routes/_dashboard/emails/templates/index'
import { Route as DashboardEmailsListsIndexRouteImport } from './routes/_dashboard/emails/lists/index'
import { Route as DashboardEmailsEmailsIndexRouteImport } from './routes/_dashboard/emails/emails/index'
import { Route as DashboardTribePostsCreateRouteImport } from './routes/_dashboard/tribe/posts/create'
import { Route as DashboardTribeMembershipTiersCreateRouteImport } from './routes/_dashboard/tribe/membership-tiers/create'
import { Route as DashboardStoreProductsCeateRouteImport } from './routes/_dashboard/store/products/ceate'
import { Route as DashboardStoreOrdersOrderIdRouteImport } from './routes/_dashboard/store/orders/$orderId'
import { Route as DashboardStoreMusicCreateRouteImport } from './routes/_dashboard/store/music/create'
import { Route as DashboardSmartLinksLinksCreateRouteImport } from './routes/_dashboard/smart-links/links/create'
import { Route as DashboardEventsListEventIdRouteImport } from './routes/_dashboard/events/list/$eventId'
import { Route as DashboardEmailsEmailsCreateRouteImport } from './routes/_dashboard/emails/emails/create'
import { Route as DashboardEventsListCreateIndexRouteImport } from './routes/_dashboard/events/list/create/index'
import { Route as DashboardWebsiteThemesSlugPreviewRouteImport } from './routes/_dashboard/website/themes/$slug.preview'
import { Route as DashboardWebsiteHomeVersionIdEditRouteImport } from './routes/_dashboard/website/home/$versionId.edit'
import { Route as DashboardTribePostsPostIdEditRouteImport } from './routes/_dashboard/tribe/posts/$postId.edit'
import { Route as DashboardStoreProductsProductIdEditRouteImport } from './routes/_dashboard/store/products/$productId.edit'
import { Route as DashboardStoreMusicProductIdEditRouteImport } from './routes/_dashboard/store/music/$productId.edit'
import { Route as DashboardSmartLinksTemplatesSlugPreviewRouteImport } from './routes/_dashboard/smart-links/templates/$slug.preview'
import { Route as DashboardSmartLinksLinksSmartLinkIdEditRouteImport } from './routes/_dashboard/smart-links/links/$smartLinkId.edit'
import { Route as DashboardSmartLinksLinksSmartLinkIdAnalyticsRouteImport } from './routes/_dashboard/smart-links/links/$smartLinkId.analytics'
import { Route as DashboardEmailsTemplatesTemplateIdEditRouteImport } from './routes/_dashboard/emails/templates/$templateId.edit'
import { Route as DashboardEmailsEmailsEmailIdReportRouteImport } from './routes/_dashboard/emails/emails/$emailId.report'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardTribeIndexRoute = DashboardTribeIndexRouteImport.update({
  id: '/tribe/',
  path: '/tribe/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStreamStudioRoute = DashboardStreamStudioRouteImport.update({
  id: '/stream/studio',
  path: '/stream/studio',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStreamListRoute = DashboardStreamListRouteImport.update({
  id: '/stream/list',
  path: '/stream/list',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWebsiteThemesIndexRoute =
  DashboardWebsiteThemesIndexRouteImport.update({
    id: '/website/themes/',
    path: '/website/themes/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardWebsiteMessagesIndexRoute =
  DashboardWebsiteMessagesIndexRouteImport.update({
    id: '/website/messages/',
    path: '/website/messages/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardWebsiteHomeIndexRoute =
  DashboardWebsiteHomeIndexRouteImport.update({
    id: '/website/home/',
    path: '/website/home/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardWebsiteAnalyticsIndexRoute =
  DashboardWebsiteAnalyticsIndexRouteImport.update({
    id: '/website/analytics/',
    path: '/website/analytics/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTribePostsIndexRoute =
  DashboardTribePostsIndexRouteImport.update({
    id: '/tribe/posts/',
    path: '/tribe/posts/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTribeMessagesIndexRoute =
  DashboardTribeMessagesIndexRouteImport.update({
    id: '/tribe/messages/',
    path: '/tribe/messages/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTribeMembershipTiersIndexRoute =
  DashboardTribeMembershipTiersIndexRouteImport.update({
    id: '/tribe/membership-tiers/',
    path: '/tribe/membership-tiers/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTribeMembersIndexRoute =
  DashboardTribeMembersIndexRouteImport.update({
    id: '/tribe/members/',
    path: '/tribe/members/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardStoreSettingsIndexRoute =
  DashboardStoreSettingsIndexRouteImport.update({
    id: '/store/settings/',
    path: '/store/settings/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardStoreProductsIndexRoute =
  DashboardStoreProductsIndexRouteImport.update({
    id: '/store/products/',
    path: '/store/products/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardStoreOrdersIndexRoute =
  DashboardStoreOrdersIndexRouteImport.update({
    id: '/store/orders/',
    path: '/store/orders/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardStoreMusicIndexRoute =
  DashboardStoreMusicIndexRouteImport.update({
    id: '/store/music/',
    path: '/store/music/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSocialMediaConnectionsIndexRoute =
  DashboardSocialMediaConnectionsIndexRouteImport.update({
    id: '/social-media/connections/',
    path: '/social-media/connections/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSmartLinksTemplatesIndexRoute =
  DashboardSmartLinksTemplatesIndexRouteImport.update({
    id: '/smart-links/templates/',
    path: '/smart-links/templates/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSmartLinksLinksIndexRoute =
  DashboardSmartLinksLinksIndexRouteImport.update({
    id: '/smart-links/links/',
    path: '/smart-links/links/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEventsSalesIndexRoute =
  DashboardEventsSalesIndexRouteImport.update({
    id: '/events/sales/',
    path: '/events/sales/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEventsListIndexRoute =
  DashboardEventsListIndexRouteImport.update({
    id: '/events/list/',
    path: '/events/list/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailsTemplatesIndexRoute =
  DashboardEmailsTemplatesIndexRouteImport.update({
    id: '/emails/templates/',
    path: '/emails/templates/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailsListsIndexRoute =
  DashboardEmailsListsIndexRouteImport.update({
    id: '/emails/lists/',
    path: '/emails/lists/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailsEmailsIndexRoute =
  DashboardEmailsEmailsIndexRouteImport.update({
    id: '/emails/emails/',
    path: '/emails/emails/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTribePostsCreateRoute =
  DashboardTribePostsCreateRouteImport.update({
    id: '/tribe/posts/create',
    path: '/tribe/posts/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTribeMembershipTiersCreateRoute =
  DashboardTribeMembershipTiersCreateRouteImport.update({
    id: '/tribe/membership-tiers/create',
    path: '/tribe/membership-tiers/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardStoreProductsCeateRoute =
  DashboardStoreProductsCeateRouteImport.update({
    id: '/store/products/ceate',
    path: '/store/products/ceate',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardStoreOrdersOrderIdRoute =
  DashboardStoreOrdersOrderIdRouteImport.update({
    id: '/store/orders/$orderId',
    path: '/store/orders/$orderId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardStoreMusicCreateRoute =
  DashboardStoreMusicCreateRouteImport.update({
    id: '/store/music/create',
    path: '/store/music/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSmartLinksLinksCreateRoute =
  DashboardSmartLinksLinksCreateRouteImport.update({
    id: '/smart-links/links/create',
    path: '/smart-links/links/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEventsListEventIdRoute =
  DashboardEventsListEventIdRouteImport.update({
    id: '/events/list/$eventId',
    path: '/events/list/$eventId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailsEmailsCreateRoute =
  DashboardEmailsEmailsCreateRouteImport.update({
    id: '/emails/emails/create',
    path: '/emails/emails/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEventsListCreateIndexRoute =
  DashboardEventsListCreateIndexRouteImport.update({
    id: '/events/list/create/',
    path: '/events/list/create/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardWebsiteThemesSlugPreviewRoute =
  DashboardWebsiteThemesSlugPreviewRouteImport.update({
    id: '/website/themes/$slug/preview',
    path: '/website/themes/$slug/preview',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardWebsiteHomeVersionIdEditRoute =
  DashboardWebsiteHomeVersionIdEditRouteImport.update({
    id: '/website/home/$versionId/edit',
    path: '/website/home/$versionId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTribePostsPostIdEditRoute =
  DashboardTribePostsPostIdEditRouteImport.update({
    id: '/tribe/posts/$postId/edit',
    path: '/tribe/posts/$postId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardStoreProductsProductIdEditRoute =
  DashboardStoreProductsProductIdEditRouteImport.update({
    id: '/store/products/$productId/edit',
    path: '/store/products/$productId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardStoreMusicProductIdEditRoute =
  DashboardStoreMusicProductIdEditRouteImport.update({
    id: '/store/music/$productId/edit',
    path: '/store/music/$productId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSmartLinksTemplatesSlugPreviewRoute =
  DashboardSmartLinksTemplatesSlugPreviewRouteImport.update({
    id: '/smart-links/templates/$slug/preview',
    path: '/smart-links/templates/$slug/preview',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSmartLinksLinksSmartLinkIdEditRoute =
  DashboardSmartLinksLinksSmartLinkIdEditRouteImport.update({
    id: '/smart-links/links/$smartLinkId/edit',
    path: '/smart-links/links/$smartLinkId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSmartLinksLinksSmartLinkIdAnalyticsRoute =
  DashboardSmartLinksLinksSmartLinkIdAnalyticsRouteImport.update({
    id: '/smart-links/links/$smartLinkId/analytics',
    path: '/smart-links/links/$smartLinkId/analytics',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailsTemplatesTemplateIdEditRoute =
  DashboardEmailsTemplatesTemplateIdEditRouteImport.update({
    id: '/emails/templates/$templateId/edit',
    path: '/emails/templates/$templateId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailsEmailsEmailIdReportRoute =
  DashboardEmailsEmailsEmailIdReportRouteImport.update({
    id: '/emails/emails/$emailId/report',
    path: '/emails/emails/$emailId/report',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof DashboardIndexRoute
  '/stream/list': typeof DashboardStreamListRoute
  '/stream/studio': typeof DashboardStreamStudioRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/tribe': typeof DashboardTribeIndexRoute
  '/emails/emails/create': typeof DashboardEmailsEmailsCreateRoute
  '/events/list/$eventId': typeof DashboardEventsListEventIdRoute
  '/smart-links/links/create': typeof DashboardSmartLinksLinksCreateRoute
  '/store/music/create': typeof DashboardStoreMusicCreateRoute
  '/store/orders/$orderId': typeof DashboardStoreOrdersOrderIdRoute
  '/store/products/ceate': typeof DashboardStoreProductsCeateRoute
  '/tribe/membership-tiers/create': typeof DashboardTribeMembershipTiersCreateRoute
  '/tribe/posts/create': typeof DashboardTribePostsCreateRoute
  '/emails/emails': typeof DashboardEmailsEmailsIndexRoute
  '/emails/lists': typeof DashboardEmailsListsIndexRoute
  '/emails/templates': typeof DashboardEmailsTemplatesIndexRoute
  '/events/list': typeof DashboardEventsListIndexRoute
  '/events/sales': typeof DashboardEventsSalesIndexRoute
  '/smart-links/links': typeof DashboardSmartLinksLinksIndexRoute
  '/smart-links/templates': typeof DashboardSmartLinksTemplatesIndexRoute
  '/social-media/connections': typeof DashboardSocialMediaConnectionsIndexRoute
  '/store/music': typeof DashboardStoreMusicIndexRoute
  '/store/orders': typeof DashboardStoreOrdersIndexRoute
  '/store/products': typeof DashboardStoreProductsIndexRoute
  '/store/settings': typeof DashboardStoreSettingsIndexRoute
  '/tribe/members': typeof DashboardTribeMembersIndexRoute
  '/tribe/membership-tiers': typeof DashboardTribeMembershipTiersIndexRoute
  '/tribe/messages': typeof DashboardTribeMessagesIndexRoute
  '/tribe/posts': typeof DashboardTribePostsIndexRoute
  '/website/analytics': typeof DashboardWebsiteAnalyticsIndexRoute
  '/website/home': typeof DashboardWebsiteHomeIndexRoute
  '/website/messages': typeof DashboardWebsiteMessagesIndexRoute
  '/website/themes': typeof DashboardWebsiteThemesIndexRoute
  '/emails/emails/$emailId/report': typeof DashboardEmailsEmailsEmailIdReportRoute
  '/emails/templates/$templateId/edit': typeof DashboardEmailsTemplatesTemplateIdEditRoute
  '/smart-links/links/$smartLinkId/analytics': typeof DashboardSmartLinksLinksSmartLinkIdAnalyticsRoute
  '/smart-links/links/$smartLinkId/edit': typeof DashboardSmartLinksLinksSmartLinkIdEditRoute
  '/smart-links/templates/$slug/preview': typeof DashboardSmartLinksTemplatesSlugPreviewRoute
  '/store/music/$productId/edit': typeof DashboardStoreMusicProductIdEditRoute
  '/store/products/$productId/edit': typeof DashboardStoreProductsProductIdEditRoute
  '/tribe/posts/$postId/edit': typeof DashboardTribePostsPostIdEditRoute
  '/website/home/$versionId/edit': typeof DashboardWebsiteHomeVersionIdEditRoute
  '/website/themes/$slug/preview': typeof DashboardWebsiteThemesSlugPreviewRoute
  '/events/list/create': typeof DashboardEventsListCreateIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof DashboardIndexRoute
  '/stream/list': typeof DashboardStreamListRoute
  '/stream/studio': typeof DashboardStreamStudioRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/tribe': typeof DashboardTribeIndexRoute
  '/emails/emails/create': typeof DashboardEmailsEmailsCreateRoute
  '/events/list/$eventId': typeof DashboardEventsListEventIdRoute
  '/smart-links/links/create': typeof DashboardSmartLinksLinksCreateRoute
  '/store/music/create': typeof DashboardStoreMusicCreateRoute
  '/store/orders/$orderId': typeof DashboardStoreOrdersOrderIdRoute
  '/store/products/ceate': typeof DashboardStoreProductsCeateRoute
  '/tribe/membership-tiers/create': typeof DashboardTribeMembershipTiersCreateRoute
  '/tribe/posts/create': typeof DashboardTribePostsCreateRoute
  '/emails/emails': typeof DashboardEmailsEmailsIndexRoute
  '/emails/lists': typeof DashboardEmailsListsIndexRoute
  '/emails/templates': typeof DashboardEmailsTemplatesIndexRoute
  '/events/list': typeof DashboardEventsListIndexRoute
  '/events/sales': typeof DashboardEventsSalesIndexRoute
  '/smart-links/links': typeof DashboardSmartLinksLinksIndexRoute
  '/smart-links/templates': typeof DashboardSmartLinksTemplatesIndexRoute
  '/social-media/connections': typeof DashboardSocialMediaConnectionsIndexRoute
  '/store/music': typeof DashboardStoreMusicIndexRoute
  '/store/orders': typeof DashboardStoreOrdersIndexRoute
  '/store/products': typeof DashboardStoreProductsIndexRoute
  '/store/settings': typeof DashboardStoreSettingsIndexRoute
  '/tribe/members': typeof DashboardTribeMembersIndexRoute
  '/tribe/membership-tiers': typeof DashboardTribeMembershipTiersIndexRoute
  '/tribe/messages': typeof DashboardTribeMessagesIndexRoute
  '/tribe/posts': typeof DashboardTribePostsIndexRoute
  '/website/analytics': typeof DashboardWebsiteAnalyticsIndexRoute
  '/website/home': typeof DashboardWebsiteHomeIndexRoute
  '/website/messages': typeof DashboardWebsiteMessagesIndexRoute
  '/website/themes': typeof DashboardWebsiteThemesIndexRoute
  '/emails/emails/$emailId/report': typeof DashboardEmailsEmailsEmailIdReportRoute
  '/emails/templates/$templateId/edit': typeof DashboardEmailsTemplatesTemplateIdEditRoute
  '/smart-links/links/$smartLinkId/analytics': typeof DashboardSmartLinksLinksSmartLinkIdAnalyticsRoute
  '/smart-links/links/$smartLinkId/edit': typeof DashboardSmartLinksLinksSmartLinkIdEditRoute
  '/smart-links/templates/$slug/preview': typeof DashboardSmartLinksTemplatesSlugPreviewRoute
  '/store/music/$productId/edit': typeof DashboardStoreMusicProductIdEditRoute
  '/store/products/$productId/edit': typeof DashboardStoreProductsProductIdEditRoute
  '/tribe/posts/$postId/edit': typeof DashboardTribePostsPostIdEditRoute
  '/website/home/$versionId/edit': typeof DashboardWebsiteHomeVersionIdEditRoute
  '/website/themes/$slug/preview': typeof DashboardWebsiteThemesSlugPreviewRoute
  '/events/list/create': typeof DashboardEventsListCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/stream/list': typeof DashboardStreamListRoute
  '/_dashboard/stream/studio': typeof DashboardStreamStudioRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_dashboard/tribe/': typeof DashboardTribeIndexRoute
  '/_dashboard/emails/emails/create': typeof DashboardEmailsEmailsCreateRoute
  '/_dashboard/events/list/$eventId': typeof DashboardEventsListEventIdRoute
  '/_dashboard/smart-links/links/create': typeof DashboardSmartLinksLinksCreateRoute
  '/_dashboard/store/music/create': typeof DashboardStoreMusicCreateRoute
  '/_dashboard/store/orders/$orderId': typeof DashboardStoreOrdersOrderIdRoute
  '/_dashboard/store/products/ceate': typeof DashboardStoreProductsCeateRoute
  '/_dashboard/tribe/membership-tiers/create': typeof DashboardTribeMembershipTiersCreateRoute
  '/_dashboard/tribe/posts/create': typeof DashboardTribePostsCreateRoute
  '/_dashboard/emails/emails/': typeof DashboardEmailsEmailsIndexRoute
  '/_dashboard/emails/lists/': typeof DashboardEmailsListsIndexRoute
  '/_dashboard/emails/templates/': typeof DashboardEmailsTemplatesIndexRoute
  '/_dashboard/events/list/': typeof DashboardEventsListIndexRoute
  '/_dashboard/events/sales/': typeof DashboardEventsSalesIndexRoute
  '/_dashboard/smart-links/links/': typeof DashboardSmartLinksLinksIndexRoute
  '/_dashboard/smart-links/templates/': typeof DashboardSmartLinksTemplatesIndexRoute
  '/_dashboard/social-media/connections/': typeof DashboardSocialMediaConnectionsIndexRoute
  '/_dashboard/store/music/': typeof DashboardStoreMusicIndexRoute
  '/_dashboard/store/orders/': typeof DashboardStoreOrdersIndexRoute
  '/_dashboard/store/products/': typeof DashboardStoreProductsIndexRoute
  '/_dashboard/store/settings/': typeof DashboardStoreSettingsIndexRoute
  '/_dashboard/tribe/members/': typeof DashboardTribeMembersIndexRoute
  '/_dashboard/tribe/membership-tiers/': typeof DashboardTribeMembershipTiersIndexRoute
  '/_dashboard/tribe/messages/': typeof DashboardTribeMessagesIndexRoute
  '/_dashboard/tribe/posts/': typeof DashboardTribePostsIndexRoute
  '/_dashboard/website/analytics/': typeof DashboardWebsiteAnalyticsIndexRoute
  '/_dashboard/website/home/': typeof DashboardWebsiteHomeIndexRoute
  '/_dashboard/website/messages/': typeof DashboardWebsiteMessagesIndexRoute
  '/_dashboard/website/themes/': typeof DashboardWebsiteThemesIndexRoute
  '/_dashboard/emails/emails/$emailId/report': typeof DashboardEmailsEmailsEmailIdReportRoute
  '/_dashboard/emails/templates/$templateId/edit': typeof DashboardEmailsTemplatesTemplateIdEditRoute
  '/_dashboard/smart-links/links/$smartLinkId/analytics': typeof DashboardSmartLinksLinksSmartLinkIdAnalyticsRoute
  '/_dashboard/smart-links/links/$smartLinkId/edit': typeof DashboardSmartLinksLinksSmartLinkIdEditRoute
  '/_dashboard/smart-links/templates/$slug/preview': typeof DashboardSmartLinksTemplatesSlugPreviewRoute
  '/_dashboard/store/music/$productId/edit': typeof DashboardStoreMusicProductIdEditRoute
  '/_dashboard/store/products/$productId/edit': typeof DashboardStoreProductsProductIdEditRoute
  '/_dashboard/tribe/posts/$postId/edit': typeof DashboardTribePostsPostIdEditRoute
  '/_dashboard/website/home/$versionId/edit': typeof DashboardWebsiteHomeVersionIdEditRoute
  '/_dashboard/website/themes/$slug/preview': typeof DashboardWebsiteThemesSlugPreviewRoute
  '/_dashboard/events/list/create/': typeof DashboardEventsListCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/'
    | '/stream/list'
    | '/stream/studio'
    | '/settings'
    | '/tribe'
    | '/emails/emails/create'
    | '/events/list/$eventId'
    | '/smart-links/links/create'
    | '/store/music/create'
    | '/store/orders/$orderId'
    | '/store/products/ceate'
    | '/tribe/membership-tiers/create'
    | '/tribe/posts/create'
    | '/emails/emails'
    | '/emails/lists'
    | '/emails/templates'
    | '/events/list'
    | '/events/sales'
    | '/smart-links/links'
    | '/smart-links/templates'
    | '/social-media/connections'
    | '/store/music'
    | '/store/orders'
    | '/store/products'
    | '/store/settings'
    | '/tribe/members'
    | '/tribe/membership-tiers'
    | '/tribe/messages'
    | '/tribe/posts'
    | '/website/analytics'
    | '/website/home'
    | '/website/messages'
    | '/website/themes'
    | '/emails/emails/$emailId/report'
    | '/emails/templates/$templateId/edit'
    | '/smart-links/links/$smartLinkId/analytics'
    | '/smart-links/links/$smartLinkId/edit'
    | '/smart-links/templates/$slug/preview'
    | '/store/music/$productId/edit'
    | '/store/products/$productId/edit'
    | '/tribe/posts/$postId/edit'
    | '/website/home/$versionId/edit'
    | '/website/themes/$slug/preview'
    | '/events/list/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/'
    | '/stream/list'
    | '/stream/studio'
    | '/settings'
    | '/tribe'
    | '/emails/emails/create'
    | '/events/list/$eventId'
    | '/smart-links/links/create'
    | '/store/music/create'
    | '/store/orders/$orderId'
    | '/store/products/ceate'
    | '/tribe/membership-tiers/create'
    | '/tribe/posts/create'
    | '/emails/emails'
    | '/emails/lists'
    | '/emails/templates'
    | '/events/list'
    | '/events/sales'
    | '/smart-links/links'
    | '/smart-links/templates'
    | '/social-media/connections'
    | '/store/music'
    | '/store/orders'
    | '/store/products'
    | '/store/settings'
    | '/tribe/members'
    | '/tribe/membership-tiers'
    | '/tribe/messages'
    | '/tribe/posts'
    | '/website/analytics'
    | '/website/home'
    | '/website/messages'
    | '/website/themes'
    | '/emails/emails/$emailId/report'
    | '/emails/templates/$templateId/edit'
    | '/smart-links/links/$smartLinkId/analytics'
    | '/smart-links/links/$smartLinkId/edit'
    | '/smart-links/templates/$slug/preview'
    | '/store/music/$productId/edit'
    | '/store/products/$productId/edit'
    | '/tribe/posts/$postId/edit'
    | '/website/home/$versionId/edit'
    | '/website/themes/$slug/preview'
    | '/events/list/create'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_dashboard/'
    | '/_dashboard/stream/list'
    | '/_dashboard/stream/studio'
    | '/_dashboard/settings/'
    | '/_dashboard/tribe/'
    | '/_dashboard/emails/emails/create'
    | '/_dashboard/events/list/$eventId'
    | '/_dashboard/smart-links/links/create'
    | '/_dashboard/store/music/create'
    | '/_dashboard/store/orders/$orderId'
    | '/_dashboard/store/products/ceate'
    | '/_dashboard/tribe/membership-tiers/create'
    | '/_dashboard/tribe/posts/create'
    | '/_dashboard/emails/emails/'
    | '/_dashboard/emails/lists/'
    | '/_dashboard/emails/templates/'
    | '/_dashboard/events/list/'
    | '/_dashboard/events/sales/'
    | '/_dashboard/smart-links/links/'
    | '/_dashboard/smart-links/templates/'
    | '/_dashboard/social-media/connections/'
    | '/_dashboard/store/music/'
    | '/_dashboard/store/orders/'
    | '/_dashboard/store/products/'
    | '/_dashboard/store/settings/'
    | '/_dashboard/tribe/members/'
    | '/_dashboard/tribe/membership-tiers/'
    | '/_dashboard/tribe/messages/'
    | '/_dashboard/tribe/posts/'
    | '/_dashboard/website/analytics/'
    | '/_dashboard/website/home/'
    | '/_dashboard/website/messages/'
    | '/_dashboard/website/themes/'
    | '/_dashboard/emails/emails/$emailId/report'
    | '/_dashboard/emails/templates/$templateId/edit'
    | '/_dashboard/smart-links/links/$smartLinkId/analytics'
    | '/_dashboard/smart-links/links/$smartLinkId/edit'
    | '/_dashboard/smart-links/templates/$slug/preview'
    | '/_dashboard/store/music/$productId/edit'
    | '/_dashboard/store/products/$productId/edit'
    | '/_dashboard/tribe/posts/$postId/edit'
    | '/_dashboard/website/home/$versionId/edit'
    | '/_dashboard/website/themes/$slug/preview'
    | '/_dashboard/events/list/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/tribe/': {
      id: '/_dashboard/tribe/'
      path: '/tribe'
      fullPath: '/tribe'
      preLoaderRoute: typeof DashboardTribeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/stream/studio': {
      id: '/_dashboard/stream/studio'
      path: '/stream/studio'
      fullPath: '/stream/studio'
      preLoaderRoute: typeof DashboardStreamStudioRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/stream/list': {
      id: '/_dashboard/stream/list'
      path: '/stream/list'
      fullPath: '/stream/list'
      preLoaderRoute: typeof DashboardStreamListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/website/themes/': {
      id: '/_dashboard/website/themes/'
      path: '/website/themes'
      fullPath: '/website/themes'
      preLoaderRoute: typeof DashboardWebsiteThemesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/website/messages/': {
      id: '/_dashboard/website/messages/'
      path: '/website/messages'
      fullPath: '/website/messages'
      preLoaderRoute: typeof DashboardWebsiteMessagesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/website/home/': {
      id: '/_dashboard/website/home/'
      path: '/website/home'
      fullPath: '/website/home'
      preLoaderRoute: typeof DashboardWebsiteHomeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/website/analytics/': {
      id: '/_dashboard/website/analytics/'
      path: '/website/analytics'
      fullPath: '/website/analytics'
      preLoaderRoute: typeof DashboardWebsiteAnalyticsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/tribe/posts/': {
      id: '/_dashboard/tribe/posts/'
      path: '/tribe/posts'
      fullPath: '/tribe/posts'
      preLoaderRoute: typeof DashboardTribePostsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/tribe/messages/': {
      id: '/_dashboard/tribe/messages/'
      path: '/tribe/messages'
      fullPath: '/tribe/messages'
      preLoaderRoute: typeof DashboardTribeMessagesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/tribe/membership-tiers/': {
      id: '/_dashboard/tribe/membership-tiers/'
      path: '/tribe/membership-tiers'
      fullPath: '/tribe/membership-tiers'
      preLoaderRoute: typeof DashboardTribeMembershipTiersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/tribe/members/': {
      id: '/_dashboard/tribe/members/'
      path: '/tribe/members'
      fullPath: '/tribe/members'
      preLoaderRoute: typeof DashboardTribeMembersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/store/settings/': {
      id: '/_dashboard/store/settings/'
      path: '/store/settings'
      fullPath: '/store/settings'
      preLoaderRoute: typeof DashboardStoreSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/store/products/': {
      id: '/_dashboard/store/products/'
      path: '/store/products'
      fullPath: '/store/products'
      preLoaderRoute: typeof DashboardStoreProductsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/store/orders/': {
      id: '/_dashboard/store/orders/'
      path: '/store/orders'
      fullPath: '/store/orders'
      preLoaderRoute: typeof DashboardStoreOrdersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/store/music/': {
      id: '/_dashboard/store/music/'
      path: '/store/music'
      fullPath: '/store/music'
      preLoaderRoute: typeof DashboardStoreMusicIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/social-media/connections/': {
      id: '/_dashboard/social-media/connections/'
      path: '/social-media/connections'
      fullPath: '/social-media/connections'
      preLoaderRoute: typeof DashboardSocialMediaConnectionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/smart-links/templates/': {
      id: '/_dashboard/smart-links/templates/'
      path: '/smart-links/templates'
      fullPath: '/smart-links/templates'
      preLoaderRoute: typeof DashboardSmartLinksTemplatesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/smart-links/links/': {
      id: '/_dashboard/smart-links/links/'
      path: '/smart-links/links'
      fullPath: '/smart-links/links'
      preLoaderRoute: typeof DashboardSmartLinksLinksIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/events/sales/': {
      id: '/_dashboard/events/sales/'
      path: '/events/sales'
      fullPath: '/events/sales'
      preLoaderRoute: typeof DashboardEventsSalesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/events/list/': {
      id: '/_dashboard/events/list/'
      path: '/events/list'
      fullPath: '/events/list'
      preLoaderRoute: typeof DashboardEventsListIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/emails/templates/': {
      id: '/_dashboard/emails/templates/'
      path: '/emails/templates'
      fullPath: '/emails/templates'
      preLoaderRoute: typeof DashboardEmailsTemplatesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/emails/lists/': {
      id: '/_dashboard/emails/lists/'
      path: '/emails/lists'
      fullPath: '/emails/lists'
      preLoaderRoute: typeof DashboardEmailsListsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/emails/emails/': {
      id: '/_dashboard/emails/emails/'
      path: '/emails/emails'
      fullPath: '/emails/emails'
      preLoaderRoute: typeof DashboardEmailsEmailsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/tribe/posts/create': {
      id: '/_dashboard/tribe/posts/create'
      path: '/tribe/posts/create'
      fullPath: '/tribe/posts/create'
      preLoaderRoute: typeof DashboardTribePostsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/tribe/membership-tiers/create': {
      id: '/_dashboard/tribe/membership-tiers/create'
      path: '/tribe/membership-tiers/create'
      fullPath: '/tribe/membership-tiers/create'
      preLoaderRoute: typeof DashboardTribeMembershipTiersCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/store/products/ceate': {
      id: '/_dashboard/store/products/ceate'
      path: '/store/products/ceate'
      fullPath: '/store/products/ceate'
      preLoaderRoute: typeof DashboardStoreProductsCeateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/store/orders/$orderId': {
      id: '/_dashboard/store/orders/$orderId'
      path: '/store/orders/$orderId'
      fullPath: '/store/orders/$orderId'
      preLoaderRoute: typeof DashboardStoreOrdersOrderIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/store/music/create': {
      id: '/_dashboard/store/music/create'
      path: '/store/music/create'
      fullPath: '/store/music/create'
      preLoaderRoute: typeof DashboardStoreMusicCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/smart-links/links/create': {
      id: '/_dashboard/smart-links/links/create'
      path: '/smart-links/links/create'
      fullPath: '/smart-links/links/create'
      preLoaderRoute: typeof DashboardSmartLinksLinksCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/events/list/$eventId': {
      id: '/_dashboard/events/list/$eventId'
      path: '/events/list/$eventId'
      fullPath: '/events/list/$eventId'
      preLoaderRoute: typeof DashboardEventsListEventIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/emails/emails/create': {
      id: '/_dashboard/emails/emails/create'
      path: '/emails/emails/create'
      fullPath: '/emails/emails/create'
      preLoaderRoute: typeof DashboardEmailsEmailsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/events/list/create/': {
      id: '/_dashboard/events/list/create/'
      path: '/events/list/create'
      fullPath: '/events/list/create'
      preLoaderRoute: typeof DashboardEventsListCreateIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/website/themes/$slug/preview': {
      id: '/_dashboard/website/themes/$slug/preview'
      path: '/website/themes/$slug/preview'
      fullPath: '/website/themes/$slug/preview'
      preLoaderRoute: typeof DashboardWebsiteThemesSlugPreviewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/website/home/$versionId/edit': {
      id: '/_dashboard/website/home/$versionId/edit'
      path: '/website/home/$versionId/edit'
      fullPath: '/website/home/$versionId/edit'
      preLoaderRoute: typeof DashboardWebsiteHomeVersionIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/tribe/posts/$postId/edit': {
      id: '/_dashboard/tribe/posts/$postId/edit'
      path: '/tribe/posts/$postId/edit'
      fullPath: '/tribe/posts/$postId/edit'
      preLoaderRoute: typeof DashboardTribePostsPostIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/store/products/$productId/edit': {
      id: '/_dashboard/store/products/$productId/edit'
      path: '/store/products/$productId/edit'
      fullPath: '/store/products/$productId/edit'
      preLoaderRoute: typeof DashboardStoreProductsProductIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/store/music/$productId/edit': {
      id: '/_dashboard/store/music/$productId/edit'
      path: '/store/music/$productId/edit'
      fullPath: '/store/music/$productId/edit'
      preLoaderRoute: typeof DashboardStoreMusicProductIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/smart-links/templates/$slug/preview': {
      id: '/_dashboard/smart-links/templates/$slug/preview'
      path: '/smart-links/templates/$slug/preview'
      fullPath: '/smart-links/templates/$slug/preview'
      preLoaderRoute: typeof DashboardSmartLinksTemplatesSlugPreviewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/smart-links/links/$smartLinkId/edit': {
      id: '/_dashboard/smart-links/links/$smartLinkId/edit'
      path: '/smart-links/links/$smartLinkId/edit'
      fullPath: '/smart-links/links/$smartLinkId/edit'
      preLoaderRoute: typeof DashboardSmartLinksLinksSmartLinkIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/smart-links/links/$smartLinkId/analytics': {
      id: '/_dashboard/smart-links/links/$smartLinkId/analytics'
      path: '/smart-links/links/$smartLinkId/analytics'
      fullPath: '/smart-links/links/$smartLinkId/analytics'
      preLoaderRoute: typeof DashboardSmartLinksLinksSmartLinkIdAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/emails/templates/$templateId/edit': {
      id: '/_dashboard/emails/templates/$templateId/edit'
      path: '/emails/templates/$templateId/edit'
      fullPath: '/emails/templates/$templateId/edit'
      preLoaderRoute: typeof DashboardEmailsTemplatesTemplateIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/emails/emails/$emailId/report': {
      id: '/_dashboard/emails/emails/$emailId/report'
      path: '/emails/emails/$emailId/report'
      fullPath: '/emails/emails/$emailId/report'
      preLoaderRoute: typeof DashboardEmailsEmailsEmailIdReportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardStreamListRoute: typeof DashboardStreamListRoute
  DashboardStreamStudioRoute: typeof DashboardStreamStudioRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardTribeIndexRoute: typeof DashboardTribeIndexRoute
  DashboardEmailsEmailsCreateRoute: typeof DashboardEmailsEmailsCreateRoute
  DashboardEventsListEventIdRoute: typeof DashboardEventsListEventIdRoute
  DashboardSmartLinksLinksCreateRoute: typeof DashboardSmartLinksLinksCreateRoute
  DashboardStoreMusicCreateRoute: typeof DashboardStoreMusicCreateRoute
  DashboardStoreOrdersOrderIdRoute: typeof DashboardStoreOrdersOrderIdRoute
  DashboardStoreProductsCeateRoute: typeof DashboardStoreProductsCeateRoute
  DashboardTribeMembershipTiersCreateRoute: typeof DashboardTribeMembershipTiersCreateRoute
  DashboardTribePostsCreateRoute: typeof DashboardTribePostsCreateRoute
  DashboardEmailsEmailsIndexRoute: typeof DashboardEmailsEmailsIndexRoute
  DashboardEmailsListsIndexRoute: typeof DashboardEmailsListsIndexRoute
  DashboardEmailsTemplatesIndexRoute: typeof DashboardEmailsTemplatesIndexRoute
  DashboardEventsListIndexRoute: typeof DashboardEventsListIndexRoute
  DashboardEventsSalesIndexRoute: typeof DashboardEventsSalesIndexRoute
  DashboardSmartLinksLinksIndexRoute: typeof DashboardSmartLinksLinksIndexRoute
  DashboardSmartLinksTemplatesIndexRoute: typeof DashboardSmartLinksTemplatesIndexRoute
  DashboardSocialMediaConnectionsIndexRoute: typeof DashboardSocialMediaConnectionsIndexRoute
  DashboardStoreMusicIndexRoute: typeof DashboardStoreMusicIndexRoute
  DashboardStoreOrdersIndexRoute: typeof DashboardStoreOrdersIndexRoute
  DashboardStoreProductsIndexRoute: typeof DashboardStoreProductsIndexRoute
  DashboardStoreSettingsIndexRoute: typeof DashboardStoreSettingsIndexRoute
  DashboardTribeMembersIndexRoute: typeof DashboardTribeMembersIndexRoute
  DashboardTribeMembershipTiersIndexRoute: typeof DashboardTribeMembershipTiersIndexRoute
  DashboardTribeMessagesIndexRoute: typeof DashboardTribeMessagesIndexRoute
  DashboardTribePostsIndexRoute: typeof DashboardTribePostsIndexRoute
  DashboardWebsiteAnalyticsIndexRoute: typeof DashboardWebsiteAnalyticsIndexRoute
  DashboardWebsiteHomeIndexRoute: typeof DashboardWebsiteHomeIndexRoute
  DashboardWebsiteMessagesIndexRoute: typeof DashboardWebsiteMessagesIndexRoute
  DashboardWebsiteThemesIndexRoute: typeof DashboardWebsiteThemesIndexRoute
  DashboardEmailsEmailsEmailIdReportRoute: typeof DashboardEmailsEmailsEmailIdReportRoute
  DashboardEmailsTemplatesTemplateIdEditRoute: typeof DashboardEmailsTemplatesTemplateIdEditRoute
  DashboardSmartLinksLinksSmartLinkIdAnalyticsRoute: typeof DashboardSmartLinksLinksSmartLinkIdAnalyticsRoute
  DashboardSmartLinksLinksSmartLinkIdEditRoute: typeof DashboardSmartLinksLinksSmartLinkIdEditRoute
  DashboardSmartLinksTemplatesSlugPreviewRoute: typeof DashboardSmartLinksTemplatesSlugPreviewRoute
  DashboardStoreMusicProductIdEditRoute: typeof DashboardStoreMusicProductIdEditRoute
  DashboardStoreProductsProductIdEditRoute: typeof DashboardStoreProductsProductIdEditRoute
  DashboardTribePostsPostIdEditRoute: typeof DashboardTribePostsPostIdEditRoute
  DashboardWebsiteHomeVersionIdEditRoute: typeof DashboardWebsiteHomeVersionIdEditRoute
  DashboardWebsiteThemesSlugPreviewRoute: typeof DashboardWebsiteThemesSlugPreviewRoute
  DashboardEventsListCreateIndexRoute: typeof DashboardEventsListCreateIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardStreamListRoute: DashboardStreamListRoute,
  DashboardStreamStudioRoute: DashboardStreamStudioRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardTribeIndexRoute: DashboardTribeIndexRoute,
  DashboardEmailsEmailsCreateRoute: DashboardEmailsEmailsCreateRoute,
  DashboardEventsListEventIdRoute: DashboardEventsListEventIdRoute,
  DashboardSmartLinksLinksCreateRoute: DashboardSmartLinksLinksCreateRoute,
  DashboardStoreMusicCreateRoute: DashboardStoreMusicCreateRoute,
  DashboardStoreOrdersOrderIdRoute: DashboardStoreOrdersOrderIdRoute,
  DashboardStoreProductsCeateRoute: DashboardStoreProductsCeateRoute,
  DashboardTribeMembershipTiersCreateRoute:
    DashboardTribeMembershipTiersCreateRoute,
  DashboardTribePostsCreateRoute: DashboardTribePostsCreateRoute,
  DashboardEmailsEmailsIndexRoute: DashboardEmailsEmailsIndexRoute,
  DashboardEmailsListsIndexRoute: DashboardEmailsListsIndexRoute,
  DashboardEmailsTemplatesIndexRoute: DashboardEmailsTemplatesIndexRoute,
  DashboardEventsListIndexRoute: DashboardEventsListIndexRoute,
  DashboardEventsSalesIndexRoute: DashboardEventsSalesIndexRoute,
  DashboardSmartLinksLinksIndexRoute: DashboardSmartLinksLinksIndexRoute,
  DashboardSmartLinksTemplatesIndexRoute:
    DashboardSmartLinksTemplatesIndexRoute,
  DashboardSocialMediaConnectionsIndexRoute:
    DashboardSocialMediaConnectionsIndexRoute,
  DashboardStoreMusicIndexRoute: DashboardStoreMusicIndexRoute,
  DashboardStoreOrdersIndexRoute: DashboardStoreOrdersIndexRoute,
  DashboardStoreProductsIndexRoute: DashboardStoreProductsIndexRoute,
  DashboardStoreSettingsIndexRoute: DashboardStoreSettingsIndexRoute,
  DashboardTribeMembersIndexRoute: DashboardTribeMembersIndexRoute,
  DashboardTribeMembershipTiersIndexRoute:
    DashboardTribeMembershipTiersIndexRoute,
  DashboardTribeMessagesIndexRoute: DashboardTribeMessagesIndexRoute,
  DashboardTribePostsIndexRoute: DashboardTribePostsIndexRoute,
  DashboardWebsiteAnalyticsIndexRoute: DashboardWebsiteAnalyticsIndexRoute,
  DashboardWebsiteHomeIndexRoute: DashboardWebsiteHomeIndexRoute,
  DashboardWebsiteMessagesIndexRoute: DashboardWebsiteMessagesIndexRoute,
  DashboardWebsiteThemesIndexRoute: DashboardWebsiteThemesIndexRoute,
  DashboardEmailsEmailsEmailIdReportRoute:
    DashboardEmailsEmailsEmailIdReportRoute,
  DashboardEmailsTemplatesTemplateIdEditRoute:
    DashboardEmailsTemplatesTemplateIdEditRoute,
  DashboardSmartLinksLinksSmartLinkIdAnalyticsRoute:
    DashboardSmartLinksLinksSmartLinkIdAnalyticsRoute,
  DashboardSmartLinksLinksSmartLinkIdEditRoute:
    DashboardSmartLinksLinksSmartLinkIdEditRoute,
  DashboardSmartLinksTemplatesSlugPreviewRoute:
    DashboardSmartLinksTemplatesSlugPreviewRoute,
  DashboardStoreMusicProductIdEditRoute: DashboardStoreMusicProductIdEditRoute,
  DashboardStoreProductsProductIdEditRoute:
    DashboardStoreProductsProductIdEditRoute,
  DashboardTribePostsPostIdEditRoute: DashboardTribePostsPostIdEditRoute,
  DashboardWebsiteHomeVersionIdEditRoute:
    DashboardWebsiteHomeVersionIdEditRoute,
  DashboardWebsiteThemesSlugPreviewRoute:
    DashboardWebsiteThemesSlugPreviewRoute,
  DashboardEventsListCreateIndexRoute: DashboardEventsListCreateIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
